### ISSUE TITLE
Risanje zemljevida

### ISSUE THREAD

**Issue by oskarvavtar** [oskarvavtar/APPR-2020-21#1]
Imam težavo z risanjem zemljevida. Risanja sem se lotil po naslednji metodi (najdeni na internetu):

Najprej v datoteko `uvoz` uvozim shapefile:
```
shapefile <- readOGR(dsn="podatki/shapefiles",
                     layer = "NUTS_Level_2__January_2018__Boundaries")
mapdata <- tidy(shapefile, region="nuts218nm")
```

Nato `mapdata` združim s tabelo v kateri so imena grofij in število festivalov v njih:
```
zdruzeni_tabeli_zemljevid <- join(mapdata, grofije_tabela, by="id")
```

Nato naredim še naslednje:
```
zemljevid_festivalov <- ggplot() +
  geom_polygon(data = zdruzeni_tabeli_zemljevid, aes(x = long, y = lat, group = group, fill = "Število festivalov"), color = "#FFFFFF", size = 0.25) +
  scale_fill_discrete()
```

Bojim se, da je neustrezna celotna metoda, saj ima dokument `mapdata` več kot 3 miljone vrstic (verjetno zaradi barvanja?) in predvidevam, da to ni ravno dobro kompatibilno z mojo tabelo `grofije_tabela`, ki ima le 12 vrstic. Združena tabela `zdruzena_tabela_zemljevid` sicer dobi stolpec `Število festivalov` vendar ima povsod vrednost `NA`. 

Vesel bi bil alternativne metode, vendar nikjer nisem našel dobre alternative za risanje UK z delitvijo po grofijah.

**Comment by jaanos** [comment]
Najprej, zemljevida ne nalagaj v repozitorij (pravzaprav ti pravila v `.gitignore` to preprečujejo), pač pa za uvoz uporabi funkcijo `uvozi.zemljevid` (najbolje bo, da jo [posodobiš](https://github.com/oskarvavtar/APPR-2020-21/compare/master...jaanos:zemljevid-kodiranje?expand=1)).

Če dobiš iz zemljevida tri milijone vrstic, je ta najbrž res prevelik. Svetujem, da uporabiš tega:
```R
mapdata <- uvozi.zemljevid("https://biogeo.ucdavis.edu/data/gadm3.6/shp/gadm36_GBR_shp.zip",
                           "gadm36_GBR_2", encoding="UTF-8")
```
Potem lahko nanj narišeš svoje podatke - morda bo bolje, da uporabiš kar `tmap`:
```R
tm_shape(merge(mapdata, grofije_tabela, by.x="NAME_2", by.y="id")) +
  tm_polygons("Število festivalov")
```
Naj opozorim, da se vsa imena iz podatkov ne pojavijo v zemljevidu, tako da bo potrebno poiskati ustrezna imena in poskrbeti za ujemanje (morda bo najbolje dodati še en stolpec k zemljevidu).

**Comment by oskarvavtar** [comment]
Hvala, ta zemljevid lepo deluje in izriše podatke, a nastane en nov problem. 

Ta zeljevid ne izriše striktno grofij, temveč administrativno delitev, posledično so nekatere grofije razdeljene na manj delčkov. Del podatkov zato ne prepozna (npr. Berkshire je razdeljen na West Berkshire, Reading, Wokingham in še dve drugi enoti). 

Ali morda obstaja kakšna metoda, da bi to lahko združil, ali bi bolje bolje kar na roko popraviti `grofije_tabela` (manj idealno, saj sem želel še narediti primerjavo med št. festivalov in socioekonomskimi dejavniki).  Verjetno bi bilo idealno najti nov zemljevid, a s tem res še nisem imel sreče.

**Comment by jaanos** [comment]
Najbolje bo, da si pripraviš en vektor, v katerem navedeš ustrezne grofije, in ga uporabiš, da dodaš stolpec z grofijo v zemljevid, npr.
```R
scotland <- mapdata[mapdata$NAME_1 == "Scotland", ]$NAME_2 # regije Škotske
zamenjava <- setNames(rep("Scotland", length(scotland)), scotland) %>%
  c("West Berkshire"="Berkshire",
    "Reading"="Berkshire",
    "Wokingham"="Berkshire",
    ...)
mapdata$grofija <- zamenjava[as.character(mapdata$NAME_2)] %>% coalesce(mapdata$NAME_2)
```
Funkcija `coalesce` poskrbi za zamenjavo `NA` s podano vrednostjo - v tem primeru se torej za regije, ki jih ne navedeš v `zamenjava`, uporabi kar vrednost iz `NAME_2`.

Potem lahko narišeš zemljevid, pri čemer združuješ po tem novem stolpcu. Morda lahko tudi izključiš risanje robov, da ne bo videti "notranjih meja" grofij:
```R
tm_shape(merge(mapdata, grofije_tabela, by.x="grofija", by.y="id")) +
    tm_polygons("Število festivalov", border.col=NULL)
```

**Comment by oskarvavtar** [comment]
Zdaj deluje super, hvala za pomoč.
