### ISSUE TITLE
Shiny, napaka v ustvarjanju tabele

### ISSUE THREAD

**Issue by oskarvavtar** [oskarvavtar/APPR-2020-21#3]
V shinyju pišem tabelo, ki bi kazala po desetletjih, koliko izvajalcev je bilo v času nastopa določene starosti (preverjam ali se izvajalci starajo...) kot `input` vzamem desetletje (v UI imam drop-down, kjer na izbiro `1970-a`, `1980-a`,...).

Naj omenim, da je zadeva že delovala, a sem na neki točki spreminjal imena spremenljivke `podatki`, od takrat naprej stvar ne deluje več (sumim, da sem nekaj ponesreči izbrisal in zdaj ne opazim kaj). Koda je napisana takole:
```
vektor <- rep(1, length(izvajalci_ostalo$Starost))
podatki <- izvajalci_ostalo %>% 
  mutate(Desetletje=(Leto%/%10*10)) 
podatki$Pojavitev <- vektor 
podatki <- podatki %>%
  filter(Desetletje == input$Desetletje) %>%
  select(Starost, Pojavitev) %>%
  group_by(Starost) %>%
  summarise(Število=sum(Pojavitev))
    
ggplot(data=podatki, aes(x=Starost, y=Število)) +
  geom_col()
```
Težava nastane pri delu 
```
summarise(Število=sum(Pojavitev))
```
Namesto da bi summarise (kot je to počel prej), za vsako možno starost seštel vse pojavitve (torej vse enke vrstic, ki imajo pod `Starost` isto vrednost), zdaj sešteje kar vse enke, ne glede na starost ter se stolpca `Starost` znebi.

**Comment by jaanos** [comment]
Težava se pojavi zato, ker v knjižnici `uvozi.zemljevid` uvoziš knjižnico `plyr`, ki povozi nekatere funkcije iz knjižnice `dplyr`, kot npr. `mutate`, `rename` in `summarise`. Uvoz knjižnice `plyr` torej raje odstrani - kolikor vidim, vse deluje tudi brez nje.

Sicer pa za štetje vrstic ni potrebno seštevati enic, pač pa to lahko narediš s funkcijo `n`:
```R
    izvajalci_ostalo %>%
      filter(Leto%/%10*10 == input$Desetletje) %>%
      group_by(Starost) %>%
      summarise(Število=n()) %>%
    ggplot(aes(x=Starost, y=Število)) +
      geom_col()
```

Še enostavneje gre z `geom_bar`:
```R
    izvajalci_ostalo %>%
      filter(Leto%/%10*10 == input$Desetletje) %>%
      ggplot(aes(x=Starost)) +
      geom_bar() + ylab("Število")
```

Mimogrede, v poročilu se sklicuješ na spremenljivko `pogostost_rock`, ki je nikjer pred tem ne definiraš.

**Comment by oskarvavtar** [comment]
Super, hvala, res je bila težava zaradi knjižnice `plyr`. Sem uporabil metodo s funkcijo `n`, je vseeno bolj čisto. Hvala za opozorilo glede `pogostost_rock`, funkcija je prej obstajala, sem jo zbrisal ko sem zadevo posplošil in pozabil da se v poročilo sklicujem na tisto specifično.
