### ISSUE TITLE
Rmd: object not found

### ISSUE THREAD

**Issue by oskarvavtar** [oskarvavtar/APPR-2020-21#4]
V datoteko `projekt.Rmd` skušam vklučiti mojo Shiny analizo. Ko datoteko zeženem mi napiše
```
Error in select: object 'zanri' not found
```
Če napišem `zanri` v konzolo mi tabelo lepo izriše. Tudi Shiny sam po sebi normalno deluje.

**Comment by jaanos** [comment]
Problem je v tem, da se na razpredelnico `zanri` prvič sklicuješ tukaj:
https://github.com/oskarvavtar/APPR-2020-21/blob/d98b8666f51a3237bd8a12e134112f0960299501/vizualizacija/vizualizacija.r#L4-L5
Definiraš jo pa šele tu:
https://github.com/oskarvavtar/APPR-2020-21/blob/d98b8666f51a3237bd8a12e134112f0960299501/vizualizacija/vizualizacija.r#L416-L428
Treba bo torej zamenjati vrstni red (poleg tega še enkrat vmes uporabiš razpredelnico `podatki`, ki na tistem mestu seveda še ne bo definirana). Mimogrede svetujem, da razpredelnico `zanri` spraviš v obliko *tidy data* - torej namesto stolpca za vsak žanr naj bo en stolpec z žanrom in eden s pogostostjo. Tako bo mogoče na istem grafu primerjati pogostosti več žanrov skozi desetletja.

**Comment by oskarvavtar** [comment]
Hvala, sem pozabil izbrisati tisti razdelek, uporabil sem ga zgolj za testiranje kode za `server.R`. V primeru `podatki` pa sem le pozabil stvar zamenjati s `pogostost_rock_tabela`.

Ali mislite, da bi bila bistvena razlika, če spremenim `zanri` v *tidy data*? Tabele namreč nikoli zares ne uporabljam v celoti, le z izbranim desetletjem, vrsto ter žanrom, na tisti točki pa (če prav razumem) že je v *tidy* obliki.

**Comment by jaanos** [comment]
Mislim, da je vseeno bolje, da imaš podatke v obliki *tidy data* - tudi, če trenutno take oblike ne potrebuješ nujno, bo morda prišla prav, če se odločiš narediti še kaj drugega.
