### ISSUE TITLE
Zadnji vprašanji pred oddajo

### ISSUE THREAD

**Issue by oskarvavtar** [oskarvavtar/APPR-2020-21#5]
Počasi končujem projekt in imam še zadnji dve vprašanji - en problem in eno manj nujno (oblikovno) stvar:

* Prvi problem je podoben kot zadnjič. V `projekt.Rmd` skušam vpeljati grafa `povprecne_starosti` in `povprecne_starosti_leta`, ki sem ju narisal v `analiza.r`. Zopet mi R Markdown vrne 
```
 Error in select: object povprecne_starosti not found
```
enako tudi za `povprecne_starosti_leta`, ko sem jo poskušal vpeljati samostojno.
Pogledal sem že po kodi, da nebi bila podobna težava kot zadnjič, a tokrat tega nisem nikjer drugje klical.

* Drugo vprašanje je oblikovno, glede `projekt.Rmd`. Zanima me ali je v R markdownu mogoče postaviti figure zraven teksta. V začetku poročila sem namreč naštel festivale iz katerih so podatki ter napisal grofije v katerih se dogajajo. Razmišljal sem da bi bilo fino dati tam zraven (po principu side-by-side) `zemljevid`, ki prikazuje lokacije festivalov po grofijah. Tisti seznam je tako ali tako dokaj ozek, prav tako pa `zemljevid`. Zato se mi zdi postavitev tam dosti bolj smiselno, kot da bi `zemljevid` žalostno sedel nekje sredi poročila.

**Comment by jaanos** [comment]
Napako dobiš, ker nikjer ne kličeš `analiza.r`. Če to storiš pred izrisom grafov, bo delovalo.

Ker je (R)Markdown v osnovi le predprocesor za HTML, lahko za stvari, ki jih ne moreš doseči z enostavnim Markdownom, uporabiš oblikovanje HTML. En enostaven (ne nujno najboljši) način, da dosežeš, kar želiš, je ta, da uporabiš tabelo z eno vrstico in dvema stolpcema, npr.
~~~html
<table>
  <tr>
    <td width="50%">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </td>
    <td width="50%">
```{r zemljevid}
zemljevid
```
    </td>
  </tr>
</table>
~~~
Morda se lahko še malo poigraš (ali uporabiš kateri drug pristop), da narediš tako, kot si si zamislil.

**Comment by oskarvavtar** [comment]
Sem se odločil, da bom raje dal zemljevid kar pod seznam. Ta pristop je deloval super, vendar je šel po gobe, ko sem spremenil `zemljevid` v interaktivnega. Po tem je stvar delovala le, če sem imel zunaj tabele še enkrat uvožen isti zemljevid, ko sem pa tistega zunanjega zakomentiral, je delovati nehal tudi tisti v tabeli.

Pojavil pa se je še en problem. Pri analizi podatkov uvozim dva grafa, pod njima pa je še komentar. Ko uvozim na vrh poročila `zemljevid` prikazuje poročilo le prvi graf. Če uvoz `zemljevida` zakomentiram pa se spet normalno pokaže tudi drugi graf ter komentar pod njima.

**Comment by jaanos** [comment]
Nisem čisto prepričan, zakaj se to zgodi - očitno gre za hrošča nekje v interakciji med knjižnicami `knitr`, `tmap`/`leaflet` in `shiny`. Ena možnost, kako se težavi izogneš, je ta, da zemljevid prikažeš znotraj aplikacije Shiny, npr.
~~~R
```{r zemljevid}
shinyApp(shinyUI(tmapOutput("zemljevid")),
         shinyServer(function(input, output) {
           output$zemljevid <- renderTmap(zemljevid)
         }),
         options=list(height=420))
```
~~~

Svetujem še, da pri definiciji zemljevida k `tm_polygons` dodaš še parameter npr. `group="Število festivalov"` in tako določiš ime plasti (ta se prikaže, če greš z miško čez ikono pod gumboma za povečavo).

**Comment by oskarvavtar** [comment]
Super, hvala, deluje zdaj super. Sem uporabil tudi predlog glede `group`, hvala za idejo. 

Bom zdaj odprl nov issue kot uradno oddajo naloge.
