### ISSUE TITLE
Oddaja naloge

### ISSUE THREAD

**Issue by oskarvavtar** [oskarvavtar/APPR-2020-21#6]
Sporočam, da je zdaj celotno poročilo deluje kot sem si zamislil in nalogo oddajam. Stestiral sem tudi z binderjem, tudi tam se stvar normalno zažene.

**Comment by jaanos** [comment]
V redu, sem dodal povezavo na repozitorij za zagovore, tako da se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

**Comment by oskarvavtar** [comment]
Sem se spomnil še, da sem pozabil dodati zaključek. Ta je zdaj dodan in že na repozitoriju.

**Comment by jaanos** [comment]
V redu, bom posodobil povezavo.

**Comment by oskarvavtar** [comment]
Ali je alen.orbanic@fmf.uni-lj.si ustrezen profesorjev naslov? Za ustni izpit sem pisal že teden nazaj pa še nisem dobil odgovora. Dvomim, da bi moj mail pristal v spamu, saj sem pisal iz univerzitetnega naslova, možno pa tudi, da je prišlo do kakšne druge napake.

**Comment by jaanos** [comment]
Je pravi naslov, ja. Morda je @alenFMF zaseden, pa še ni uspel odgovoriti - lahko mu tudi poskusiš še enkrat pisati.

**Comment by alenFMF** [comment]
Se opravičujem, sem spregledal email iz prejšnjega tedna. Sem @oskarvavtar  ravno odpisal.
